% Generated by purerl version 0.0.24
-module(app@ps).
-export([main/0]).
-compile(nowarn_shadow_vars).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(no_auto_import).
-include("./app.hrl").

-ifndef(PURERL_MEMOIZE).
-define(MEMOIZE(X), X).
-else.
-define(MEMOIZE, memoize).
memoize(X) -> X.
-endif.
%-file("/Users/0x1/Documents/htdocs/altbak.pub/src/App.purs", 18).
-spec main() -> fun(() -> any()).
main() -> fun
  __do() -> 
  ((test_astTree@ps:describe())()),
  ((test_astTree@ps:act())()),
  ((test_fib@ps:describe())()),
  ((test_fib@ps:act())()),
  ((test_listOps@ps:describe())()),
  ((test_listOps@ps:act())()),
  ((test_tCO@ps:describe())()),
  ((test_tCO@ps:act())()),
  ((test_records@ps:describe())()),
  ((test_records@ps:act())()),
  ((test_ackermann@ps:describe())()),
  ((test_ackermann@ps:act())()),
  ((test_church@ps:describe())()),
  ((test_church@ps:act())()),
  ((test_primes@ps:describe())()),
  ((test_primes@ps:act())()),
  ((test_rBTree@ps:describe())()),
  ((test_rBTree@ps:act())()),
  ((test_polymorphism@ps:describe())()),
  ((test_polymorphism@ps:act())()),
  ((test_stateMonad@ps:describe())()),
  ((test_stateMonad@ps:act())()),
  ((test_lazyEvaluation@ps:describe())()),
  ((test_lazyEvaluation@ps:act())())
end.
